### ISSUE TITLE
Android Build Problems

### ISSUE THREAD

**Issue by unitydev1234** [ElasticSea/unity-fracture#7]
This works really well in the unity editor and with x64 windows builds, however, when I build to android I run into problems.

I used android logcat to pinpoint exactly what was happening. Here is the output from the log file.

![image](https://user-images.githubusercontent.com/71948497/94351159-60012b00-0013-11eb-9a86-eb107758cf61.png)

Essentially the NvBlastExtUnity_x64.dll isn't getting included in the build. Do you have any thoughts on how to fix this?

**Comment by ElasticSea** [comment]
I originally got the dll here https://forum.unity.com/threads/nvidia-blast.472623 If you want to use it on other platforms you have to get the correct dll or build the nvblast project yourself.

**Comment by naylinhtun1** [comment]
> 

can you explain more I already try that forum link and how do I get correct dll ??

**Comment by ElasticSea** [comment]
I have no idea, you need to ask on that forum
